/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
/* Header for class com_example_lvliang_helloopencv_OpenCVClass */

using namespace cv;
#ifndef _Included_com_example_lvliang_helloopencv_OpenCVClass
#define _Included_com_example_lvliang_helloopencv_OpenCVClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lvliang_helloopencv_OpenCVClass
 * Method:    faceDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_lvliang_helloopencv_OpenCVClass_faceDetection
  (JNIEnv *, jclass, jlong);

void detect (Mat &frame);

#ifdef __cplusplus
}
#endif
#endif
